config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks',
    registration: 'users/registrations'
  }
  #, skip: :registration

  resources :articles, only: [:show, :index]
  resources :categories, only: [:show]
  resources :projects, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :body
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  has_one_attached :image

  define_easy_dates do
    format_for :created_at, :format => "%A, %B %-d, %Y at%l:%M%P"
    format_for :updated_at, :format => "%A, %B %-d, %Y at%l:%M%P"
  end
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :category
  belongs_to :article
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  has_one_attached :image

  define_easy_dates do
    format_for :created_at, :format => "%A, %B %-d, %Y at%l:%M%P"
    format_for :updated_at, :format => "%A, %B %-d, %Y at%l:%M%P"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_many :projects

  # omniauthable, :confirmable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :lockable, :timeoutable

  define_easy_dates do
    format_for :created_at, :format => "%A, %B %-d, %Y at%l:%M%P"
    format_for :updated_at, :format => "%A, %B %-d, %Y at%l:%M%P"
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def new

  end

  def create

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(user)
    admin_dashboard_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(id_param[:id])
  end

  def index
    @articles = Article.all
  end

  private

    def id_param
      params.permit(:id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(id_param[:id])
    @articles = @category.articles
  end

  def id_param
    params.permit(:id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(id_params[:id])
  end

  def index
    @projects = Project.all
  end

  private

    def id_params
      params.permit(:id)
    end
end

app/controllers/projects_controllers.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(id_params[:id])
  end

  def index
    @projects = Project.all
  end

  private

    def id_params
      params.permit(:id)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag 'application' %>
  </head>

  <body>
    <div class="left">
      <div class="terminal">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>

        <%= yield %>
      </div>
    </div>

    <div class="right">
      <div class="info">
        <%= render partial: 'shared/directory' %>
      </div>
      <div class="contact">
        <%= render partial: 'shared/contact' %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_contact.html.erb
<br>
<div>Valerie Trudell</div>
<hr>
<br>
<div>
  <a href="mailto:valedithat@pm.me">Mail</a>
</div>
<br>
<div>
  <a href="https://github.com/valedithat">GitHub</a>
</div>
<br>
<div>
  <a href="https://valedithat.herokuapp.com/">Website</a>
</div>
<br>
<div>
    <a href="https://www.linkedin.com/in/valerie-trudell">Linkedin</a>
</div>
<br>
<div>location: San Jose, CA</div>
<br>

app/views/shared/_directory.html.erb
<div class="directory">
  <div class="resources">
    <div class="link"><%= link_to "Home", root_path %></div>
    <div class="link"><%= link_to "Articles", articles_path %></div>
    <div class="link"><%= link_to "Projects", projects_path %></div>
  </div>
  <hr>
  <div class="session-links">
    <% if current_user %>
      <div class="link"><%= link_to "Dashboard", admin_dashboard_path %></div>
      <div class="link"><%= link_to "Log out", destroy_user_session_path, method: :destroy %></div>
    <% else %>
      <div class="link"><%= link_to "Log in", new_user_session_path %></div>
    <% end %>
  </div>
</div>