config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks',
    registration: 'users/registrations'
  }
  #, skip: :registration

  resources :articles, only: [:show, :index]
  resources :categories, only: [:show]
  resources :projects, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :body
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  has_one_attached :image

  define_easy_dates do
    format_for :created_at, :format => "%A, %B %-d, %Y at%l:%M%P"
    format_for :updated_at, :format => "%A, %B %-d, %Y at%l:%M%P"
  end
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :category
  belongs_to :article
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  has_one_attached :image

  define_easy_dates do
    format_for :created_at, :format => "%A, %B %-d, %Y at%l:%M%P"
    format_for :updated_at, :format => "%A, %B %-d, %Y at%l:%M%P"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_many :projects

  # omniauthable, :confirmable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :lockable, :timeoutable

  define_easy_dates do
    format_for :created_at, :format => "%A, %B %-d, %Y at%l:%M%P"
    format_for :updated_at, :format => "%A, %B %-d, %Y at%l:%M%P"
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def new

  end

  def create

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(user)
    admin_dashboard_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(id_param[:id])
  end

  def index
    @articles = Article.all
  end

  private

    def id_param
      params.permit(:id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(id_param[:id])
    @articles = @category.articles
  end

  def id_param
    params.permit(:id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(id_params[:id])
  end

  def index
    @projects = Project.all
  end

  private

    def id_params
      params.permit(:id)
    end
end

app/controllers/projects_controllers.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(id_params[:id])
  end

  def index
    @projects = Project.all
  end

  private

    def id_params
      params.permit(:id)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/articles/index.html.erb
<div class="articles">
  <h1>valedithat</h1>
  <h5>Portfollio and Blogging</h5>
  <%= render partial: 'shared/articles/all_articles' %>
</div>

app/views/articles/show.html.erb
<%= render partial: 'shared/articles/article' %>

app/views/categories/show.html.erb
<div class="articles">
  <h1><%= @category.name %> Articles</h1>
  <%= render partial: 'shared/articles/all_articles' %>
</div>

app/views/projects/index.html.erb
<div>
  <h1>Projects</h1>
  <% @projects.each do |project| %>
    <div class="project">
      <h1 class="title"><%= link_to project.title, project_path(project) %></h1>
      <hr>
      <%= image_tag(project.image) if project.image.attached? %>
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<%= render partial: 'shared/projects/project', locals: { project: @project } %>

app/views/shared/articles/_all_articles.html.erb
<% @articles.each do |article| %>
  <div class="article">
    <hr>
    <div class="article_#{article.id}">
        <h3 class="title"><%= link_to article.title, article_path(article) %></h3>
        <div class="article-description"><%= article.description %></div>
    </div>
  </div>
<% end %>

app/views/shared/articles/_article.html.erb
<div class="article">
  <h1 class="title"><%= @article.title %></h1>
  <div class="article-metadata">
    <span class="date"><%= @article.formatted_created_at %></span>
    <span class="author"><%= @article.user.name %></span>
  </div>
  <div class="article-description"><%= @article.description %></div>
  <hr>
  <div class="article-meat">
    <%= image_tag(@article.image, size: '1000x600') if @article.image.attached? %>
    <div class="body"><%= @article.body %></div>
    <div class="categories">
      <% @article.categories.each do |category| %>
          <span class="category_#{category.id}"><%= category.name %></span>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/projects/_project.html.erb
<div class="project">
  <%= image_tag(project.image, size: '1000x600') if project.image.attached? %>
  <h1 class="title"><%= project.title %></h1>
  <hr>
  <div class="project-description"><%= project.description %></div>
  <div class="link"><%= link_to project.link %></div>
  <div class="project-metadata">
    <span class="date"><%= project.formatted_created_at %></span>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>